import type { Metadata } from "next";

import { createServerComponentClient } from "@supabase/auth-helpers-nextjs";
import { cookies } from "next/headers";
import AuthProvider from "@/components/AuthProvider";
import { Inter } from "next/font/google";

import "../styles/globals.css";
import ThemeToggle from "@/components/ThemeToggle";
import { getCurrentTheme } from "@/lib/colorTheme";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

// do not cache this layout
export const revalidate = 0;

export const metadata: Metadata = {
  title: "Next.js with Supabase Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerComponentClient({ cookies });

  const {
    data: { session },
  } = await supabase.auth.getSession();

  const accessToken = session?.access_token || null;
  const theme = await getCurrentTheme();

  return (
    <html lang="en" className={theme === "dark" ? "dark" : ""}>
      <body className={inter.className}>
        <AuthProvider accessToken={accessToken}>
          <div className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
            <ThemeToggle />
          </div>
        </AuthProvider>
      </body>
    </html>
  );
}
